import React, { useMemo, useState } from 'react';
import { 
  Edit, 
  Trash2, 
  FileText, 
  CheckSquare, 
  Square, 
  Eye,
  ChevronLeft,
  ChevronRight,
  FileCode
} from 'lucide-react';
import { format, parse } from 'date-fns';
import { CITTA_DISPONIBILI } from '../financialTypes';

interface Fattura {
  id: string;
  numero_fattura: string | null;
  inquilino_nome: string;
  appartamento_nome: string;
  citta: string;
  agenzia?: string;
  tipologia?: string;
  sez?: string;
  xml?: boolean;
  pdf?: boolean;
  importo_lordo: number;
  mese_competenza: string;
  stato: string;
  data_emissione: string | null;
  note: string;
  isAutoGenerated?: boolean;
}

interface FattureTabellaProps {
  fatture: Fattura[];
  selectedIds: string[];
  onSelectionChange: (ids: string[]) => void;
  onDettaglio: (id: string) => void;
  onModifica: (id: string) => void;
  onDownloadXML: (id: string) => void;
  onElimina: (id: string) => void;
  onGeneraFatture?: () => void;
}

export const FattureTabella: React.FC<FattureTabellaProps> = ({
  fatture,
  selectedIds,
  onSelectionChange,
  onDettaglio,
  onModifica,
  onDownloadXML,
  onElimina,
  onGeneraFatture
}) => {
  
  // --- Inline Filters State ---
  const [inlineFilters, setInlineFilters] = useState({
    citta: '',
    agenzia: '',
    data: '', // Date string
    tipologia: '',
    cliente: '',
    imponibile: '',
    totale: '',
    xml: false, // Boolean toggle
    pdf: false, // Boolean toggle
    mensilita: ''
  });

  // Derived unique lists for table dropdowns (could be props, but deriving here is self-contained)
  const tableAgencies = useMemo(() => Array.from(new Set(fatture.map(f => f.agenzia || 'Stanza Semplice SRL'))).sort(), [fatture]);
  const tableClients = useMemo(() => Array.from(new Set(fatture.map(f => f.inquilino_nome))).sort(), [fatture]);

  // --- Pagination State ---
  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(50);

  // --- Formatting Helpers ---
  const formatCurrency = (val: number) => 
    new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(val);

  const formatMonth = (ym: string) => {
    try {
      const date = parse(ym, 'yyyy-MM', new Date());
      return format(date, 'MM/yyyy');
    } catch { return ym; }
  };

  const formatDate = (d: string | null) => {
    if (!d) return '';
    try {
        return format(new Date(d), 'dd/MM/yyyy');
    } catch { return d; }
  };

  // --- Filtering Logic (Inline) ---
  const filteredData = useMemo(() => {
    return fatture.filter(f => {
      // 1. Dropdown Filters
      if (inlineFilters.citta && f.citta !== inlineFilters.citta) return false;
      if (inlineFilters.agenzia && (f.agenzia || 'Stanza Semplice SRL') !== inlineFilters.agenzia) return false;
      if (inlineFilters.tipologia && (f.tipologia || 'Fattura') !== inlineFilters.tipologia) return false;
      if (inlineFilters.cliente && f.inquilino_nome !== inlineFilters.cliente) return false;

      // 2. Text/Date Filters
      if (inlineFilters.data && f.data_emissione !== inlineFilters.data) return false;
      if (inlineFilters.imponibile && !f.importo_lordo.toString().startsWith(inlineFilters.imponibile)) return false;
      if (inlineFilters.totale && !f.importo_lordo.toString().startsWith(inlineFilters.totale)) return false;
      if (inlineFilters.mensilita && !formatMonth(f.mese_competenza).includes(inlineFilters.mensilita)) return false;

      // 3. Toggle Filters
      if (inlineFilters.xml && !f.xml) return false;
      if (inlineFilters.pdf && !f.pdf) return false;

      return true;
    });
  }, [fatture, inlineFilters]);

  // --- Totals Logic (on Filtered Data) ---
  const totalAmount = useMemo(() => filteredData.reduce((sum, f) => sum + f.importo_lordo, 0), [filteredData]);

  // --- Pagination Logic ---
  const totalPages = Math.ceil(filteredData.length / rowsPerPage);
  const paginatedData = useMemo(() => {
    const start = (currentPage - 1) * rowsPerPage;
    return filteredData.slice(start, start + rowsPerPage);
  }, [filteredData, currentPage, rowsPerPage]);

  const handlePageChange = (newPage: number) => {
    if (newPage > 0 && newPage <= totalPages) {
      setCurrentPage(newPage);
    }
  };

  // --- Selection Logic ---
  const allSelected = filteredData.length > 0 && filteredData.every(f => selectedIds.includes(f.id));

  const handleSelectAll = () => {
    if (allSelected) {
      onSelectionChange([]);
    } else {
      onSelectionChange(filteredData.map(f => f.id));
    }
  };

  const handleSelectOne = (id: string) => {
    if (selectedIds.includes(id)) {
      onSelectionChange(selectedIds.filter(sid => sid !== id));
    } else {
      onSelectionChange([...selectedIds, id]);
    }
  };

  const handleFilterChange = (key: string, value: any) => {
    setInlineFilters(prev => ({ ...prev, [key]: value }));
    setCurrentPage(1); // Reset page on filter
  };

  // --- Render Helpers ---
  const renderHeaderInput = (filterKey: string, widthClass: string) => {
    return (
        <input 
            type="text" 
            value={inlineFilters[filterKey as keyof typeof inlineFilters] as string}
            onChange={(e) => handleFilterChange(filterKey, e.target.value)}
            className="w-full h-6 text-[11px] bg-white border border-slate-200 rounded px-1.5 text-slate-700 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none transition-all placeholder:text-slate-300 font-medium"
            placeholder="..."
            onClick={(e) => e.stopPropagation()}
        />
    );
  };

  const renderHeaderSelect = (filterKey: string, options: string[]) => {
      return (
        <select 
            value={inlineFilters[filterKey as keyof typeof inlineFilters] as string}
            onChange={(e) => handleFilterChange(filterKey, e.target.value)}
            className="w-full h-6 text-[11px] border border-slate-200 rounded px-1 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none transition-all font-normal text-slate-700 bg-white"
            onClick={(e) => e.stopPropagation()}
        >
            <option value="">Tutti</option>
            {options.map(opt => <option key={opt} value={opt}>{opt}</option>)}
        </select>
      );
  };

  const renderHeaderToggle = (filterKey: 'xml' | 'pdf', Icon: React.ElementType, activeColorClass: string) => {
      const isActive = inlineFilters[filterKey];
      return (
          <button 
            onClick={(e) => { e.stopPropagation(); handleFilterChange(filterKey, !isActive); }}
            className={`flex items-center justify-center w-full h-6 rounded border transition-all ${isActive ? activeColorClass + ' bg-opacity-10 border-opacity-50' : 'bg-white border-slate-200 text-slate-300 hover:text-slate-500'}`}
          >
             <Icon size={14} className={isActive ? '' : ''} />
          </button>
      );
  };

  const renderBadge = (type: string) => {
    const isNC = type === 'Nota di Credito';
    return (
      <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-bold border whitespace-nowrap
        ${isNC ? 'bg-purple-50 text-purple-700 border-purple-100' : 'bg-orange-50 text-orange-700 border-orange-100'}
      `}>
        {isNC ? 'NC' : 'Fattura'}
      </span>
    );
  };

  const renderBool = (val: boolean | undefined) => (
    <span className={`font-bold text-[11px] ${val ? 'text-green-600' : 'text-red-500'}`}>
      {val ? 'Sì' : 'No'}
    </span>
  );

  if (fatture.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20 px-4 text-center bg-white rounded-xl border border-slate-200 shadow-sm mt-4">
        <div className="w-20 h-20 bg-slate-50 text-slate-300 rounded-full flex items-center justify-center mb-6">
          <FileText size={40} />
        </div>
        <h3 className="text-xl font-bold text-slate-800 mb-2">Nessuna fattura presente</h3>
        <p className="text-slate-500 max-w-sm mx-auto mb-8 text-sm">
          Non ci sono dati da mostrare. Prova a generare nuove fatture.
        </p>
        {onGeneraFatture && (
          <button 
            onClick={onGeneraFatture}
            className="px-6 py-2.5 bg-orange-500 hover:bg-orange-600 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-orange-500/20 active:scale-95"
          >
            Genera Fatture per questo mese
          </button>
        )}
      </div>
    );
  }

  // Column Order: Città, Agenzia, Data, Tipologia, Cliente, Imponibile, Totale, XML, PDF, Mensilità
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col overflow-hidden relative mt-4">
      <div className="overflow-x-auto custom-scrollbar pb-2">
        <table className="w-full text-left text-xs border-collapse min-w-[1200px]">
          <thead>
            <tr className="bg-[#F8F9FA] border-b border-slate-200">
              {/* Checkbox */}
              <th className="px-2 py-3 w-10 text-center align-bottom pb-4">
                <button onClick={handleSelectAll} className="flex items-center justify-center text-slate-400 hover:text-slate-700">
                  {allSelected ? <CheckSquare size={16} /> : <Square size={16} />}
                </button>
              </th>
              
              {/* Città */}
              <th className="px-2 py-3 align-bottom w-[100px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Città</span>
                    {renderHeaderSelect('citta', CITTA_DISPONIBILI)}
                </div>
              </th>

              {/* Agenzia */}
              <th className="px-2 py-3 align-bottom w-[140px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Agenzia</span>
                    {renderHeaderSelect('agenzia', tableAgencies)}
                </div>
              </th>

              {/* N. Fatt (Keeping implicitly as generic info, positioned here or merged) - Let's keep it visible but maybe smaller/secondary to Data */}
              <th className="px-2 py-3 align-bottom w-[80px]">
                 <div className="flex flex-col gap-2 pb-1.5">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">N. Fatt</span>
                 </div>
              </th>

              {/* Data */}
              <th className="px-2 py-3 align-bottom w-[110px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Data</span>
                    <input 
                        type="date" 
                        value={inlineFilters.data}
                        onChange={(e) => handleFilterChange('data', e.target.value)}
                        className="w-full h-6 text-[11px] border border-slate-200 rounded px-1 focus:border-orange-500 outline-none text-slate-700 bg-white"
                    />
                </div>
              </th>

              {/* Tipologia */}
              <th className="px-2 py-3 align-bottom w-[100px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Tipologia</span>
                    {renderHeaderSelect('tipologia', ['Fattura', 'Nota di Credito'])}
                </div>
              </th>

              {/* Cliente */}
              <th className="px-2 py-3 align-bottom min-w-[160px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Cliente</span>
                    {renderHeaderSelect('cliente', tableClients)}
                </div>
              </th>
              
              {/* Imponibile */}
              <th className="px-2 py-3 align-bottom w-[100px] text-right">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Imponibile</span>
                    {renderHeaderInput('imponibile', '')}
                </div>
              </th>

              {/* Totale */}
              <th className="px-2 py-3 align-bottom w-[100px] text-right">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Totale</span>
                    {renderHeaderInput('totale', '')}
                </div>
              </th>
              
              {/* XML Toggle */}
              <th className="px-2 py-3 align-bottom w-[50px] text-center">
                <div className="flex flex-col gap-2 items-center">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">XML</span>
                    {renderHeaderToggle('xml', FileCode, 'text-orange-600 border-orange-200 bg-orange-50')}
                </div>
              </th>

              {/* PDF Toggle */}
              <th className="px-2 py-3 align-bottom w-[50px] text-center">
                <div className="flex flex-col gap-2 items-center">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">PDF</span>
                    {renderHeaderToggle('pdf', FileText, 'text-red-600 border-red-200 bg-red-50')}
                </div>
              </th>

              {/* Mensilità */}
              <th className="px-2 py-3 align-bottom w-[100px]">
                <div className="flex flex-col gap-2">
                    <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider truncate">Mensilità</span>
                    {renderHeaderInput('mensilita', '')}
                </div>
              </th>

              {/* Azioni */}
              <th className="px-2 py-3 align-bottom text-right w-[100px] sticky right-0 bg-[#F8F9FA] shadow-[-4px_0_8px_-4px_rgba(0,0,0,0.1)]">
                <div className="flex flex-col gap-2 pb-1.5">
                  <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">Azioni</span>
                </div>
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {paginatedData.map((fattura) => {
              const isSelected = selectedIds.includes(fattura.id);
              const isDraft = fattura.stato === 'bozza';
              const isPaid = fattura.stato === 'pagata';
              const isEmitted = fattura.stato === 'emessa' || fattura.stato === 'inviata_sdi';
              
              // Row Styling
              let rowBorderClass = '';
              let rowBgClass = '';

              if (isDraft) rowBorderClass = 'border-l-[3px] border-l-amber-600';
              else if (isPaid) rowBorderClass = 'border-l-[3px] border-l-green-600';
              else if (isEmitted) rowBorderClass = 'border-l-[3px] border-l-orange-500';
              else if (fattura.stato === 'scartata') rowBorderClass = 'border-l-[3px] border-l-red-600';

              if (!isDraft && !isPaid && (!fattura.xml || !fattura.pdf)) {
                 rowBgClass = 'bg-red-50/40 hover:bg-red-50/60';
              } else if (fattura.isAutoGenerated) {
                 rowBgClass = 'bg-[rgba(249,115,22,0.04)]'; 
              } else {
                 rowBgClass = isSelected ? 'bg-indigo-50/60' : 'bg-white hover:bg-[#F8F7FF]';
              }

              return (
                <tr 
                  key={fattura.id} 
                  className={`
                    group transition-colors
                    ${rowBgClass}
                  `}
                >
                  <td className={`px-2 py-2.5 text-center ${rowBorderClass}`}>
                    <button 
                      onClick={() => handleSelectOne(fattura.id)}
                      className={`flex items-center justify-center transition-colors ${isSelected ? 'text-indigo-600' : 'text-slate-300 hover:text-slate-400'}`}
                    >
                      {isSelected ? <CheckSquare size={16} /> : <Square size={16} />}
                    </button>
                  </td>
                  
                  {/* Città */}
                  <td className="px-2 py-2.5 font-medium text-slate-900 truncate">
                    {fattura.citta}
                  </td>

                  {/* Agenzia */}
                  <td className="px-2 py-2.5 text-[13px] text-slate-500 truncate" title={fattura.agenzia}>
                    {fattura.agenzia || 'Stanza Semplice SRL'}
                  </td>

                  {/* N. Fattura (Moved here, kept simple) */}
                  <td className="px-2 py-2.5 font-mono text-slate-600 truncate">
                    {fattura.isAutoGenerated 
                      ? <span className="text-slate-400 font-normal italic text-[11px]">— (bozza)</span> 
                      : (fattura.numero_fattura || '-')
                    }
                  </td>

                  {/* Data */}
                  <td className="px-2 py-2.5 text-slate-700 truncate">
                    {formatDate(fattura.data_emissione) || '-'}
                  </td>

                  {/* Tipologia */}
                  <td className="px-2 py-2.5">
                    {renderBadge(fattura.tipologia || 'Fattura')}
                  </td>

                  {/* Cliente */}
                  <td className="px-2 py-2.5 font-medium text-orange-600 hover:text-orange-800 hover:underline cursor-pointer truncate max-w-[200px]" onClick={() => onDettaglio(fattura.id)}>
                    {fattura.inquilino_nome}
                  </td>

                  {/* Imponibile */}
                  <td className="px-2 py-2.5 text-right font-mono text-slate-900">
                    {formatCurrency(fattura.importo_lordo)}
                  </td>

                  {/* Totale */}
                  <td className="px-2 py-2.5 text-right font-bold text-slate-900">
                    {formatCurrency(fattura.importo_lordo)}
                  </td>

                  {/* XML */}
                  <td className="px-2 py-2.5 text-center">
                    {isDraft ? <span className="text-slate-300">-</span> : renderBool(fattura.xml)}
                  </td>

                  {/* PDF */}
                  <td className="px-2 py-2.5 text-center">
                    {isDraft ? <span className="text-slate-300">-</span> : renderBool(fattura.pdf)}
                  </td>

                  {/* Mensilità */}
                  <td className="px-2 py-2.5 text-slate-600 truncate max-w-[120px]" title={formatMonth(fattura.mese_competenza)}>
                    {formatMonth(fattura.mese_competenza)}
                  </td>

                  {/* Azioni */}
                  <td className={`px-2 py-2.5 text-right sticky right-0 bg-white group-hover:bg-[#F8F7FF] shadow-[-4px_0_8px_-4px_rgba(0,0,0,0.1)] ${isSelected ? 'bg-indigo-50/60' : ''}`}>
                    <div className="flex items-center justify-end gap-1.5">
                      <button 
                        onClick={() => onModifica(fattura.id)}
                        disabled={!isDraft}
                        className={`p-1 rounded hover:bg-slate-100 transition-colors ${isDraft ? 'text-slate-500 hover:text-orange-600' : 'text-slate-200 cursor-not-allowed'}`}
                        title="Modifica"
                      >
                        <Edit size={14} />
                      </button>
                      <button 
                        onClick={() => onDettaglio(fattura.id)}
                        className="p-1 rounded hover:bg-slate-100 transition-colors text-slate-500 hover:text-blue-600"
                        title="Dettaglio"
                      >
                        <Eye size={14} />
                      </button>
                      {isDraft && (
                        <button 
                          onClick={() => onElimina(fattura.id)}
                          className="p-1 rounded hover:bg-slate-100 transition-colors text-slate-500 hover:text-red-600"
                          title="Elimina"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
            
            {filteredData.length === 0 && (
              <tr>
                <td colSpan={14} className="px-4 py-8 text-center text-slate-400 italic">
                  Nessun risultato corrisponde ai filtri inline.
                </td>
              </tr>
            )}
          </tbody>

          {/* 4.5 Sticky Totals Footer */}
          <tfoot className="sticky bottom-0 z-20 bg-[#F9FAFB] border-t-2 border-orange-500 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)]">
             <tr>
               <td className="px-2 py-3 font-bold text-slate-500 text-[11px] uppercase tracking-wider" colSpan={8}>
                 TOTALE ({filteredData.length} documenti)
               </td>
               <td className="px-2 py-3 text-right font-bold text-slate-900 text-xs">
                 {formatCurrency(totalAmount)}
               </td>
               <td className="px-2 py-3 text-right font-bold text-slate-900 text-xs">
                 {formatCurrency(totalAmount)}
               </td>
               <td colSpan={4}></td>
             </tr>
          </tfoot>
        </table>
      </div>

      {/* 4.3 Pagination Controls */}
      <div className="bg-white border-t border-slate-200 px-6 py-3 flex justify-between items-center text-xs text-slate-500">
        <div className="flex items-center gap-4">
           <span>
             {Math.min((currentPage - 1) * rowsPerPage + 1, filteredData.length)} – {Math.min(currentPage * rowsPerPage, filteredData.length)} di {filteredData.length}
           </span>
           <div className="flex items-center gap-2">
             <span>Righe per pagina:</span>
             <select 
               value={rowsPerPage} 
               onChange={(e) => {
                 setRowsPerPage(Number(e.target.value));
                 setCurrentPage(1);
               }}
               className="bg-slate-50 border border-slate-200 rounded px-1 py-0.5 outline-none focus:border-orange-500 cursor-pointer"
             >
               <option value={25}>25</option>
               <option value={50}>50</option>
               <option value={100}>100</option>
             </select>
           </div>
        </div>
        
        <div className="flex items-center gap-1">
           <button 
             onClick={() => handlePageChange(currentPage - 1)}
             disabled={currentPage === 1}
             className="p-1.5 rounded hover:bg-slate-100 disabled:opacity-50 disabled:cursor-not-allowed"
           >
             <ChevronLeft size={16} />
           </button>
           <span className="font-medium px-2">Pagina {currentPage}</span>
           <button 
             onClick={() => handlePageChange(currentPage + 1)}
             disabled={currentPage === totalPages}
             className="p-1.5 rounded hover:bg-slate-100 disabled:opacity-50 disabled:cursor-not-allowed"
           >
             <ChevronRight size={16} />
           </button>
        </div>
      </div>
    </div>
  );
};