import React, { useState, useMemo, useEffect } from 'react';
import { format, parseISO, isWithinInterval, isValid } from 'date-fns';
import { CheckCircle2, X, Zap, ArrowRight, AlertTriangle } from 'lucide-react';
import { FattureHeader } from '../components/FattureHeader';
import { FattureTabella } from '../components/FattureTabella';
import { ModalGeneraFatture } from '../components/ModalGeneraFatture';
import { DrawerDettaglioFattura } from '../components/DrawerDettaglioFattura';
import { MOCK_FATTURE, PRENOTAZIONI_ATTIVE } from '../financialTypes';

export const Invoices: React.FC = () => {
  // --- STATE DATI ---
  const [fatture, setFatture] = useState(MOCK_FATTURE);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  
  // --- STATE FILTRI (New Logic) ---
  const [filtroDataMode, setFiltroDataMode] = useState<'month' | 'single' | 'range'>('month');
  const [filtroData, setFiltroData] = useState<string>(format(new Date(), 'yyyy-MM')); // Default month
  const [filtroDataDa, setFiltroDataDa] = useState('');
  const [filtroDataA, setFiltroDataA] = useState('');
  
  const [filtroCitta, setFiltroCitta] = useState('');
  const [filtroAgenzia, setFiltroAgenzia] = useState('');
  const [filtroTipologia, setFiltroTipologia] = useState('');
  const [filtroCliente, setFiltroCliente] = useState('');
  const [filtroXmlOnly, setFiltroXmlOnly] = useState(false);
  const [filtroPdfOnly, setFiltroPdfOnly] = useState(false);

  // --- STATE UI ---
  const [isGeneraOpen, setIsGeneraOpen] = useState(false);
  const [detailId, setDetailId] = useState<string | null>(null);
  const [showSuggestionBanner, setShowSuggestionBanner] = useState(true);
  const [toast, setToast] = useState<{ visible: boolean; message: string; type: 'success' | 'error' }>({ 
    visible: false, message: '', type: 'success' 
  });

  // --- DERIVED LISTS FOR DROPDOWNS ---
  const availableAgencies = useMemo(() => {
    return Array.from(new Set(fatture.map(f => f.agenzia || 'Stanza Semplice SRL'))).sort();
  }, [fatture]);

  // Logica dinamica: Mostra solo i clienti presenti nella Città selezionata (e Agenzia se selezionata)
  const availableClients = useMemo(() => {
    let relevantFatture = fatture;
    
    // 1. Filtra per Città se selezionata
    if (filtroCitta) {
      relevantFatture = relevantFatture.filter(f => f.citta === filtroCitta);
    }
    
    // 2. Filtra per Agenzia se selezionata
    if (filtroAgenzia) {
      relevantFatture = relevantFatture.filter(f => (f.agenzia || 'Stanza Semplice SRL') === filtroAgenzia);
    }
    
    return Array.from(new Set(relevantFatture.map(f => f.inquilino_nome))).sort();
  }, [fatture, filtroCitta, filtroAgenzia]);

  // RESET AUTOMATICO CLIENTE
  // Se cambio città e il cliente selezionato non è più nella lista valida, resetto il campo cliente.
  useEffect(() => {
    if (filtroCliente && !availableClients.includes(filtroCliente)) {
      setFiltroCliente('');
    }
  }, [filtroCitta, filtroAgenzia, availableClients, filtroCliente]);


  // --- LOGIC ---

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ visible: true, message, type });
    setTimeout(() => setToast(prev => ({ ...prev, visible: false })), 3000);
  };

  // AUTO-GENERATION LOGIC (Only runs if Month Mode is active)
  useEffect(() => {
    if (filtroDataMode !== 'month' || !filtroData) return;

    const hasInvoices = fatture.some(f => f.mese_competenza === filtroData);
    
    if (!hasInvoices) {
      const selectedDate = parseISO(filtroData + '-01');
      
      const generatedDrafts = PRENOTAZIONI_ATTIVE.filter(p => {
         const start = parseISO(p.data_inizio);
         const end = parseISO(p.data_fine);
         return (selectedDate >= start || format(start, 'yyyy-MM') === filtroData) && selectedDate <= end;
      }).map((p, i) => ({
         id: `auto-${p.id}-${filtroData}`,
         numero_fattura: null,
         inquilino_nome: p.inquilino,
         inquilino_id: p.inquilino_id,
         agenzia: p.agenzia,
         citta: p.citta,
         appartamento_nome: p.appartamento,
         importo_lordo: p.canone_mensile,
         mese_competenza: filtroData,
         data_emissione: null,
         stato: 'bozza',
         tipologia: p.tipologia,
         sez: 'SUB',
         xml: false,
         pdf: false,
         note: 'Bozza suggerita automaticamente dal sistema',
         isAutoGenerated: true
      }));

      if (generatedDrafts.length > 0) {
         setFatture(prev => [...prev, ...generatedDrafts]);
         setShowSuggestionBanner(true);
      }
    }
  }, [filtroData, filtroDataMode]);

  // Reset selezione quando cambiano i filtri
  useEffect(() => {
    setSelectedIds([]);
  }, [filtroCitta, filtroAgenzia, filtroData, filtroDataDa, filtroDataA, filtroTipologia, filtroCliente]);

  // --- FILTRO DATI COMPLETO ---
  const filteredFatture = useMemo(() => {
    return fatture.filter(f => {
      // 1. Filtri Dropdown Base
      if (filtroCitta && f.citta !== filtroCitta) return false;
      if (filtroAgenzia && (f.agenzia || 'Stanza Semplice SRL') !== filtroAgenzia) return false;
      if (filtroTipologia && (f.tipologia || 'Fattura') !== filtroTipologia) return false;
      if (filtroCliente && f.inquilino_nome !== filtroCliente) return false;

      // 2. Filtro Data (Logic Switch)
      if (filtroDataMode === 'month') {
         if (f.mese_competenza !== filtroData) return false;
      } else if (filtroDataMode === 'single') {
         if (filtroData && f.data_emissione !== filtroData) return false;
      } else if (filtroDataMode === 'range') {
         if (filtroDataDa && filtroDataA && f.data_emissione) {
            const date = parseISO(f.data_emissione);
            const start = parseISO(filtroDataDa);
            const end = parseISO(filtroDataA);
            if (isValid(date) && isValid(start) && isValid(end)) {
               if (!isWithinInterval(date, { start, end })) return false;
            }
         }
      }

      // 3. Toggles XML/PDF
      if (filtroXmlOnly && !f.xml) return false;
      if (filtroPdfOnly && !f.pdf) return false;

      return true;
    });
  }, [
    fatture, filtroCitta, filtroAgenzia, filtroTipologia, filtroCliente,
    filtroDataMode, filtroData, filtroDataDa, filtroDataA,
    filtroXmlOnly, filtroPdfOnly
  ]);

  // Calcolo KPI dinamici (Based on filtered data generally, or month data specifically? 
  // Standard practice: KPI usually reflect the CURRENT view. So we use filteredFatture)
  const kpiData = useMemo(() => {
    const kpiTotal = filteredFatture.reduce((sum, inv) => sum + inv.importo_lordo, 0);
    
    const kpiToCollect = filteredFatture
      .filter(inv => inv.stato !== 'pagata' && inv.stato !== 'bozza')
      .reduce((sum, inv) => sum + inv.importo_lordo, 0);
      
    const kpiUnpaid = filteredFatture.filter(inv => 
      inv.stato === 'scartata' || (inv.stato !== 'pagata' && inv.stato !== 'bozza')
    ).length;

    return { kpiTotal, kpiToCollect, kpiUnpaid };
  }, [filteredFatture]);

  const anomaliesCount = useMemo(() => {
    return filteredFatture.filter(f => f.stato === 'emessa' && !f.xml).length;
  }, [filteredFatture]);

  const selectedDraftsCount = useMemo(() => {
    return filteredFatture.filter(f => selectedIds.includes(f.id) && f.stato === 'bozza').length;
  }, [filteredFatture, selectedIds]);

  const draftsInCurrentView = useMemo(() => {
    return filteredFatture.filter(f => f.stato === 'bozza').length;
  }, [filteredFatture]);

  const activeFattura = useMemo(() => 
    detailId ? fatture.find(f => f.id === detailId) || null : null
  , [fatture, detailId]);

  // --- HANDLERS ---

  const handleGeneraFatture = () => setIsGeneraOpen(true);

  const handleConfermaGenerazione = ({ isDraft }: { isDraft: boolean }) => {
    // Implementation same as before, simplified for this context
    setIsGeneraOpen(false);
    showToast('Fatture generate', 'success');
  };

  const handleCambioStato = (id: string, nuovoStato: string) => {
    setFatture(prev => prev.map(f => {
      if (f.id !== id) return f;
      return { ...f, stato: nuovoStato };
    }));
  };

  const handleEmitAllDrafts = () => {
    if (confirm(`Vuoi emettere tutte le ${draftsInCurrentView} bozze visibili?`)) {
      setFatture(prev => prev.map(f => {
         const isVisibleDraft = filteredFatture.some(v => v.id === f.id && v.stato === 'bozza');
         if (isVisibleDraft) {
             return { ...f, stato: 'emessa', data_emissione: format(new Date(), 'yyyy-MM-dd') };
         }
         return f;
      }));
      showToast(`${draftsInCurrentView} fatture emesse con successo!`);
      setShowSuggestionBanner(false);
    }
  };

  const handleElimina = (id: string) => {
    if (window.confirm('Eliminare bozza?')) {
      setFatture(prev => prev.filter(f => f.id !== id));
      if (detailId === id) setDetailId(null);
      setSelectedIds(prev => prev.filter(sid => sid !== id));
      showToast('Bozza eliminata');
    }
  };

  const handleBulkAction = (action: any) => {
     // Simplified bulk action handler
     showToast(`Azione ${action} eseguita su ${selectedIds.length} elementi`);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500 pb-20 relative">
      
      {/* ALERT FATTURE ANOMALE */}
      {anomaliesCount > 0 && (
        <div className="bg-[#FEF2F2] border-l-4 border-red-600 p-4 rounded-r-lg shadow-sm flex items-start gap-3 animate-in slide-in-from-top-2">
          <AlertTriangle className="text-red-600 shrink-0 mt-0.5" size={20} />
          <div>
            <h4 className="text-red-800 font-bold text-sm">Attenzione Richiesta</h4>
            <p className="text-red-700 text-xs mt-1">
              ⚠️ Ci sono <strong>{anomaliesCount} fatture emesse senza file XML</strong>. Genera i file XML prima di procedere.
            </p>
          </div>
          <button 
            onClick={() => setFiltroXmlOnly(true)}
            className="ml-auto text-xs font-bold text-red-700 underline hover:text-red-900"
          >
            Filtra Anomale
          </button>
        </div>
      )}

      {/* HEADER SEMPLIFICATO (Solo KPI e Action) */}
      <FattureHeader 
        kpiTotal={kpiData.kpiTotal}
        kpiToCollect={kpiData.kpiToCollect}
        kpiUnpaid={kpiData.kpiUnpaid}
        onGeneraFatture={handleGeneraFatture}
      />

      {/* SUGGESTION BANNER */}
      {showSuggestionBanner && draftsInCurrentView > 0 && (
        <div className="mx-0 lg:mx-1 bg-orange-50 border-l-4 border-orange-500 rounded-r-lg p-5 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4 animate-in slide-in-from-top-2">
           <div className="flex gap-4">
              <div className="p-2 bg-orange-100 rounded-full text-orange-600 shrink-0 mt-1 md:mt-0">
                <Zap size={20} fill="currentColor" />
              </div>
              <div>
                <h4 className="text-slate-800 font-bold text-sm">Hai {draftsInCurrentView} fatture pronte per l'emissione</h4>
                <p className="text-slate-600 text-xs mt-1 max-w-2xl leading-relaxed">
                   Controlla i dati e procedi con l'emissione massiva o puntuale.
                </p>
              </div>
           </div>
           
           <div className="flex items-center gap-4 w-full md:w-auto pl-12 md:pl-0">
              <button 
                onClick={handleEmitAllDrafts}
                className="flex items-center gap-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-xs font-bold transition-all shadow-md active:scale-95 whitespace-nowrap"
              >
                Emetti tutte ({draftsInCurrentView}) <ArrowRight size={14} />
              </button>
              <button 
                onClick={() => setShowSuggestionBanner(false)}
                className="text-slate-400 hover:text-slate-600 text-xs font-medium underline decoration-slate-300 underline-offset-2"
              >
                Nascondi
              </button>
           </div>
        </div>
      )}

      {/* TABELLA CON FILTRI INLINE (Gestisce i filtri autonomamente tramite stato interno per ora, 
          o idealmente dovrebbe riceverli da Invoices se decidessimo di spostarli. 
          Al momento FattureTabella ha i suoi filtri inline quindi funziona autonomamente 
          sui dati passati) */}
      <FattureTabella 
        fatture={filteredFatture}
        selectedIds={selectedIds}
        onSelectionChange={setSelectedIds}
        onDettaglio={setDetailId}
        onModifica={(id) => setDetailId(id)}
        onDownloadXML={(id) => showToast(`Download XML avviato`, 'success')}
        onElimina={handleElimina}
        onGeneraFatture={handleGeneraFatture}
      />

      <ModalGeneraFatture 
        isOpen={isGeneraOpen}
        onClose={() => setIsGeneraOpen(false)}
        onConferma={handleConfermaGenerazione}
        meseSelezionatoStr={filtroData}
      />

      <DrawerDettaglioFattura 
        fattura={activeFattura}
        onClose={() => setDetailId(null)}
        onModifica={(id) => console.log('Edit requested for', id)}
        onCambioStato={handleCambioStato}
      />

      {/* Toast Notification */}
      {toast.visible && (
        <div className="fixed bottom-8 right-8 z-[60] bg-slate-900 text-white px-4 py-3 rounded-lg shadow-xl flex items-center gap-3 animate-in slide-in-from-bottom-5">
           <div className={`p-1 rounded-full ${toast.type === 'error' ? 'bg-red-500' : 'bg-green-500'}`}>
             {toast.type === 'error' ? <X size={14} /> : <CheckCircle2 size={14} />}
           </div>
           <span className="text-sm font-semibold">{toast.message}</span>
        </div>
      )}
    </div>
  );
};